# .circleci/config.yml
version: 2.1
orbs:
  slack: circleci/slack@4.9.3
jobs:
  build:
    docker:
      - image: cimg/node:current
    steps:
      - checkout

      # Restore previous node package cache if there is one
      - restore_cache:
          key: node-{{ checksum "package-lock.json" }}

      # Install or update packages
      - run: npm ci

      # Save cache
      - save_cache:
          key: node-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

      # Store project files for the next job
      - persist_to_workspace:
          root: ~/
          paths:
            - project

  test:
    docker:
      - image: cimg/node:current

    steps:
      # Start with the initial build
      - attach_workspace:
          at: ~/

      # Run tests and save JUnit XML file
      - run: npm run mocha-junit

      # Store test artifacts and results
      - store_artifacts:
          path: results
          destination: test_results
      - store_test_results:
          path: results

  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          event: fail
          mentions: '@here'
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

workflows:
   version: 2
   full:
     jobs:
       - build
       - test:
           requires:
             - build
           context: slack-secrets
           post-steps:
             - slack/notify:
                 event: fail
                 mentions: '@here'
                 template: basic_fail_1
       - notify:
           requires:
             - test
           context: slack-secrets